import type { Metadata } from 'next'
import type { Seo } from '@/lib/sanity/models'

const clip = (s: string, max: number) => (s.length <= max ? s : `${s.slice(0, max - 1).trimEnd()}…`)

/**
 * Metadata from the Sanity `seo` object with sensible fallbacks (NFR-SEO-01): title ≤ 60 chars,
 * description ≤ 155, canonical URL, OG image (generated by `opengraph-image.tsx` unless overridden).
 */
export function buildMetadata({
  title,
  description,
  path,
  seo,
  noindex,
}: {
  title: string
  description: string
  path: string
  seo?: Seo | null
  noindex?: boolean
}): Metadata {
  const t = clip(seo?.title ?? title, 60)
  const d = clip(seo?.description ?? description, 155)
  const images = seo?.ogImage
    ? [{ url: seo.ogImage.url, width: 1200, height: 630, alt: seo.ogImage.alt || t }]
    : undefined
  return {
    title: t,
    description: d,
    alternates: { canonical: path },
    openGraph: { title: t, description: d, url: path, ...(images ? { images } : {}) },
    twitter: { title: t, description: d, ...(images ? { images } : {}) },
    ...(noindex || seo?.noindex ? { robots: { index: false, follow: true } } : {}),
  }
}
