import { block } from './portable'
import type {
  Bundle,
  ChangelogEntry,
  Faq,
  HomePage,
  ImageRef,
  LegalPage,
  License,
  Post,
  ProductCard,
  ProductDetail,
  ProductLine,
  SiteSettings,
  StackItem,
  TemplateType,
} from './models'

export { block }

/**
 * Seed catalog. Serves the storefront when CONTENT_SOURCE=fixtures (local development before a
 * Sanity project exists) and is the catalog that scripts/seed.ts mirrors into Postgres.
 *
 * Art direction (StyleGuide §8): no fabricated testimonials or metrics. Stat tiles derive their
 * numbers from this catalog; the testimonial list is intentionally empty until real, attributed
 * quotes with permission exist in Sanity. Lemon Squeezy IDs are placeholders: real IDs live in the
 * Sanity Studio, and `pnpm ls:sync` then pulls prices and limits from the store. Art is generated by
 * `pnpm gen:fixture-art` into public/fixtures.
 */

let keySeq = 0
const key = () => `k${(++keySeq).toString(36)}`

const art = (slug: string, alt: string): ImageRef => ({
  url: `/fixtures/${slug}.svg`,
  alt,
  width: 1600,
  height: 1000,
  lqip: null,
})

// ---------- Tech stack ----------
const STACK: Record<string, StackItem> = {
  next: { name: 'Next.js', slug: 'nextjs', kind: 'framework', logo: null, version: '16.3' },
  react: { name: 'React', slug: 'react', kind: 'library', logo: null, version: '19.2' },
  tailwind: { name: 'Tailwind CSS', slug: 'tailwind', kind: 'styling', logo: null, version: '4.1' },
  drizzle: { name: 'Drizzle', slug: 'drizzle', kind: 'library', logo: null, version: '0.45' },
  clerk: { name: 'Clerk', slug: 'clerk', kind: 'service', logo: null, version: '7' },
  radix: { name: 'Radix', slug: 'radix', kind: 'library', logo: null, version: '1.6' },
  motion: { name: 'Motion', slug: 'motion', kind: 'library', logo: null, version: '13' },
  astro: { name: 'Astro', slug: 'astro', kind: 'framework', logo: null, version: '6' },
  fumadocs: { name: 'Fumadocs', slug: 'fumadocs', kind: 'library', logo: null, version: '16' },
  sanity: { name: 'Sanity', slug: 'sanity', kind: 'service', logo: null, version: '6' },
  stripe: { name: 'Lemon Squeezy', slug: 'lemonsqueezy', kind: 'service', logo: null, version: null },
}

const RIGHTS: Record<License['tier'], string[]> = {
  personal: ['1 developer', '1 end product', 'Updates within the purchased major version'],
  team: ['Up to 5 developers', 'Unlimited internal and client projects', 'Updates within the purchased major version'],
  extended: [
    'Up to 25 activations',
    'End products sold to end users (SaaS, paid apps)',
    'Updates within the purchased major version',
  ],
}

let variantSeq = 100000
function licenses(prices: [number, number, number]): License[] {
  const lsProductId = 50000 + Math.floor(variantSeq / 10)
  return (['personal', 'team', 'extended'] as const).map((tier, i) => ({
    tier,
    lsProductId,
    lsVariantId: ++variantSeq,
    priceCents: prices[i]!,
    activationLimit: [1, 5, 25][i]!,
    rights: RIGHTS[tier],
    buyUrl: null,
  }))
}

type Seed = {
  slug: string
  name: string
  line: ProductLine
  templateType?: TemplateType
  tagline: string
  stack: StackItem[]
  capabilities: string[]
  prices: [number, number, number]
  popularity: number
  createdAt: string
  description: string[]
  features: ProductDetail['features']
  fileTree?: string
  demoPages?: { label: string; path: string }[]
  supportsTheme?: boolean
  components?: ProductDetail['components']
  releases: Omit<ChangelogEntry, '_id' | 'product' | 'status' | 'releaseId'>[]
}

const change = (kind: ChangelogEntry['changes'][number]['kind'], text: string, docsPath: string | null = null) => ({
  kind,
  text,
  docsPath,
})

const SEEDS: Seed[] = [
  {
    slug: 'saas-starter',
    name: 'SaaS Starter',
    line: 'boilerplate',
    tagline: 'A Next.js 16 foundation with auth, billing and multi-tenancy already wired.',
    stack: [STACK.next!, STACK.react!, STACK.tailwind!, STACK.drizzle!, STACK.clerk!, STACK.stripe!],
    capabilities: ['auth', 'payments', 'multi-tenant', 'dark-mode', 'i18n'],
    prices: [14900, 24900, 49900],
    popularity: 100,
    createdAt: '2025-11-04T09:00:00Z',
    description: [
      'SaaS Starter is the codebase we would want on day one: organizations and roles, subscription billing with a customer portal, transactional email and an admin console, all typed end to end.',
      'Every integration sits behind a small interface, so swapping a provider is an adapter change, not a rewrite.',
    ],
    features: [
      {
        eyebrow: 'Auth',
        title: 'Organizations, roles and invites',
        body: 'Clerk sessions with org-scoped roles, invitations and an audited member list.',
        icon: 'users',
        size: 'lg',
      },
      {
        eyebrow: 'Billing',
        title: 'Subscriptions with dunning',
        body: 'Plans, trials, proration and failed-payment recovery with signed webhooks.',
        icon: 'credit-card',
        size: 'md',
      },
      {
        eyebrow: 'Data',
        title: 'Drizzle schema with RLS',
        body: 'Row-level security and tenant isolation tested in CI.',
        icon: 'database',
        size: 'md',
      },
      {
        eyebrow: 'DX',
        title: 'Typed end to end',
        body: 'Zod env, typed routes and a single `pnpm check` gate.',
        icon: 'shield-check',
        size: 'sm',
      },
    ],
    fileTree: `.\n├── src\n│   ├── app\n│   ├── components\n│   ├── db\n│   ├── emails\n│   ├── lib\n│   └── server\n├── tests\n├── drizzle.config.ts\n├── next.config.ts\n└── package.json`,
    demoPages: [
      { label: 'Home', path: '/' },
      { label: 'Pricing', path: '/pricing' },
      { label: 'Dashboard', path: '/dashboard' },
      { label: 'Settings', path: '/settings' },
    ],
    supportsTheme: true,
    releases: [
      {
        version: '2.3.1',
        type: 'patch',
        releasedAt: '2026-09-18T10:00:00Z',
        title: 'Webhook retries and Node 24',
        summary: 'Idempotent billing webhooks under concurrent retries, and Node 24 LTS as the default runtime.',
        highlights: null,
        upgradeGuide: null,
        changes: [
          change('fixed', 'Concurrent webhook retries no longer create duplicate invoices'),
          change('improved', 'Node 24 LTS is the default runtime'),
        ],
        compatibility: { next: '16.3', react: '19.2', tailwind: '4.1', node: '24' },
      },
      {
        version: '2.3.0',
        type: 'minor',
        releasedAt: '2026-09-02T10:00:00Z',
        title: 'Audit log and passkeys',
        summary: 'An append-only audit log for admin actions and passkey sign-in out of the box.',
        highlights: [
          block('Every admin mutation now writes an append-only audit entry with before and after snapshots.'),
        ],
        upgradeGuide: null,
        changes: [
          change('added', 'Append-only audit log with a before/after diff viewer', '/docs/saas-starter/structure'),
          change('added', 'Passkey sign-in'),
          change('improved', 'Faster cold starts on the dashboard'),
        ],
        compatibility: { next: '16.3', react: '19.2', tailwind: '4.1', node: '22' },
      },
      {
        version: '2.2.0',
        type: 'minor',
        releasedAt: '2026-07-20T10:00:00Z',
        title: 'Usage-based billing',
        summary: 'Metered plans with usage records and invoice previews.',
        highlights: null,
        upgradeGuide: null,
        changes: [
          change('added', 'Metered billing with usage records'),
          change('fixed', 'Invoice preview rounding for yearly plans'),
        ],
        compatibility: { next: '16.2', react: '19.2', tailwind: '4.1', node: '22' },
      },
      {
        version: '2.0.0',
        type: 'major',
        releasedAt: '2026-05-12T10:00:00Z',
        title: 'Next.js 16 and Cache Components',
        summary: 'Rebuilt on Next.js 16 with Cache Components, proxy.ts and the React Compiler.',
        highlights: [block('Static shells with streamed personal data: every marketing page now prerenders.')],
        upgradeGuide: [
          block('Rename middleware.ts to proxy.ts and move authorization checks into each page and Server Action.'),
          block('Replace unstable_cache with "use cache" functions and add cacheTag() calls for every CMS query.'),
        ],
        changes: [
          change('breaking', 'middleware.ts is now proxy.ts', '/docs/saas-starter/upgrading'),
          change('breaking', 'Caching moved to "use cache" + cacheTag'),
          change('added', 'React Compiler enabled by default'),
        ],
        compatibility: { next: '16.0', react: '19.2', tailwind: '4.1', node: '22' },
      },
      {
        version: '1.9.4',
        type: 'patch',
        releasedAt: '2026-03-01T10:00:00Z',
        title: 'Security patch',
        summary: 'Stricter webhook signature comparison.',
        highlights: null,
        upgradeGuide: null,
        changes: [change('security', 'Constant-time webhook signature comparison')],
        compatibility: { next: '15.5', react: '19.1', tailwind: '4.0', node: '22' },
      },
    ],
  },
  {
    slug: 'lumen-ui',
    name: 'Lumen UI',
    line: 'ui_kit',
    tagline: 'Marketing and dashboard blocks for shadcn/ui, installable from a private registry.',
    stack: [STACK.react!, STACK.tailwind!, STACK.radix!, STACK.motion!],
    capabilities: ['dark-mode', 'animations', 'figma'],
    prices: [9900, 17900, 34900],
    popularity: 90,
    createdAt: '2025-12-10T09:00:00Z',
    description: [
      'Lumen UI is a set of production blocks built on shadcn/ui primitives: heroes, pricing tables, feature grids, stats and full dashboard layouts.',
      'Install any block with `npx shadcn add @lumira/<name>` using your license key; you own the code from then on.',
    ],
    features: [
      {
        eyebrow: 'Registry',
        title: 'Install with the shadcn CLI',
        body: 'A license-gated registry: one command per block, no copy-paste.',
        icon: 'terminal',
        size: 'lg',
      },
      {
        eyebrow: 'Theming',
        title: 'Tokens, not overrides',
        body: 'Every block reads your CSS variables; light and dark ship designed.',
        icon: 'palette',
        size: 'md',
      },
      {
        eyebrow: 'Motion',
        title: 'Spring interactions',
        body: 'Press, reveal and layout motion with reduced-motion variants.',
        icon: 'sparkles',
        size: 'md',
      },
    ],
    demoPages: [
      { label: 'Overview', path: '/' },
      { label: 'Marketing', path: '/marketing' },
      { label: 'Dashboard', path: '/dashboard' },
    ],
    supportsTheme: true,
    components: [
      {
        name: 'hero-01',
        title: 'Hero 01',
        description: 'Split hero with product shot',
        code: 'import { Button } from \'@/components/ui/button\'\n\nexport function Hero01() {\n  return (\n    <section className="grid gap-8 py-24 lg:grid-cols-2">\n      <div className="flex flex-col gap-6">\n        <h1 className="text-5xl font-semibold tracking-tight text-balance">Ship the launch page today</h1>\n        <p className="text-lg text-muted-foreground">A hero that reads your tokens.</p>\n        <Button size="lg">Get started</Button>\n      </div>\n    </section>\n  )\n}',
      },
      {
        name: 'pricing-table',
        title: 'Pricing table',
        description: 'Three tiers with a monthly/yearly toggle',
        code: null,
      },
      { name: 'feature-grid', title: 'Feature grid', description: 'Bento feature grid', code: null },
      { name: 'stats-01', title: 'Stats 01', description: 'KPI row with sparklines', code: null },
    ],
    releases: [
      {
        version: '1.4.0',
        type: 'minor',
        releasedAt: '2026-09-10T10:00:00Z',
        title: 'Dashboard blocks',
        summary: 'Twelve dashboard blocks: stat rows, activity feeds and data tables.',
        highlights: null,
        upgradeGuide: null,
        changes: [
          change('added', '12 dashboard blocks', '/docs/lumen-ui/registry'),
          change('improved', 'Chart colors follow the validated palette'),
        ],
        compatibility: { next: '16.3', react: '19.2', tailwind: '4.1', node: null },
      },
      {
        version: '1.3.2',
        type: 'patch',
        releasedAt: '2026-08-14T10:00:00Z',
        title: 'Focus rings',
        summary: 'Solid 2 px focus rings on every interactive block.',
        highlights: null,
        upgradeGuide: null,
        changes: [change('fixed', 'Focus rings reach 3:1 on every surface')],
        compatibility: { next: '16.2', react: '19.2', tailwind: '4.1', node: null },
      },
      {
        version: '1.0.0',
        type: 'major',
        releasedAt: '2026-01-20T10:00:00Z',
        title: 'Lumen UI 1.0',
        summary: 'The first stable release with 96 marketing blocks.',
        highlights: null,
        upgradeGuide: [
          block('First stable release: install blocks through the registry instead of the preview package.'),
        ],
        changes: [change('added', '96 marketing blocks'), change('added', 'License-gated shadcn registry')],
        compatibility: { next: '16.0', react: '19.2', tailwind: '4.0', node: null },
      },
    ],
  },
  {
    slug: 'motion-primitives',
    name: 'Motion Primitives',
    line: 'ui_kit',
    tagline: 'Spring-physics interaction components with designed reduced-motion variants.',
    stack: [STACK.react!, STACK.motion!, STACK.tailwind!],
    capabilities: ['animations', 'dark-mode'],
    prices: [7900, 14900, 29900],
    popularity: 60,
    createdAt: '2026-04-02T09:00:00Z',
    description: [
      'Segmented controls with gliding indicators, bottom sheets with drag-to-dismiss, number tickers and shared-element transitions, tuned with explicit spring tokens.',
    ],
    features: [
      {
        eyebrow: 'Physics',
        title: 'Spring tokens',
        body: 'Stiffness, damping and mass documented with settle times.',
        icon: 'activity',
        size: 'lg',
      },
      {
        eyebrow: 'Access',
        title: 'Reduced motion by design',
        body: 'Every component ships its reduced-motion variant.',
        icon: 'accessibility',
        size: 'md',
      },
    ],
    demoPages: [{ label: 'Gallery', path: '/' }],
    components: [
      { name: 'segmented-control', title: 'Segmented control', description: 'layoutId indicator', code: null },
      { name: 'bottom-sheet', title: 'Bottom sheet', description: 'Drag to dismiss', code: null },
    ],
    releases: [
      {
        version: '1.1.0',
        type: 'minor',
        releasedAt: '2026-09-15T10:00:00Z',
        title: 'Number ticker',
        summary: 'A KPI number ticker with tabular digits while moving.',
        highlights: null,
        upgradeGuide: null,
        changes: [change('added', 'NumberTicker component')],
        compatibility: { next: '16.3', react: '19.2', tailwind: '4.1', node: null },
      },
      {
        version: '1.0.0',
        type: 'major',
        releasedAt: '2026-04-02T10:00:00Z',
        title: 'Motion Primitives 1.0',
        summary: 'Eight interaction primitives on Motion 13.',
        highlights: null,
        upgradeGuide: [block('First stable release.')],
        changes: [change('added', '8 primitives')],
        compatibility: { next: '16.1', react: '19.2', tailwind: '4.1', node: null },
      },
    ],
  },
  {
    slug: 'folio',
    name: 'Folio',
    line: 'template',
    templateType: 'portfolio',
    tagline: 'A portfolio template for designers who code, with case studies in MDX.',
    stack: [STACK.next!, STACK.tailwind!, STACK.motion!],
    capabilities: ['dark-mode', 'animations', 'cms', 'figma'],
    prices: [5900, 9900, 19900],
    popularity: 80,
    createdAt: '2026-02-11T09:00:00Z',
    description: [
      'Folio puts the work first: full-bleed case studies, a calm index and page transitions that carry images between routes.',
    ],
    features: [
      {
        eyebrow: 'Content',
        title: 'Case studies in MDX',
        body: 'Write in Markdown, drop in galleries and before/after sliders.',
        icon: 'file-text',
        size: 'lg',
      },
      {
        eyebrow: 'Motion',
        title: 'Shared-element transitions',
        body: 'Covers morph from the index into the case study.',
        icon: 'move',
        size: 'md',
      },
    ],
    demoPages: [
      { label: 'Index', path: '/' },
      { label: 'Case study', path: '/work/atlas' },
      { label: 'About', path: '/about' },
    ],
    supportsTheme: true,
    releases: [
      {
        version: '1.2.0',
        type: 'minor',
        releasedAt: '2026-09-05T10:00:00Z',
        title: 'Before/after slider',
        summary: 'A keyboard-accessible before/after comparison for redesign case studies.',
        highlights: null,
        upgradeGuide: null,
        changes: [change('added', 'Before/after slider MDX component')],
        compatibility: { next: '16.3', react: '19.2', tailwind: '4.1', node: '22' },
      },
      {
        version: '1.0.0',
        type: 'major',
        releasedAt: '2026-02-11T10:00:00Z',
        title: 'Folio 1.0',
        summary: 'The first stable release.',
        highlights: null,
        upgradeGuide: [block('First stable release.')],
        changes: [change('added', 'Index, case study and about pages')],
        compatibility: { next: '16.1', react: '19.2', tailwind: '4.0', node: '22' },
      },
    ],
  },
  {
    slug: 'launchpad',
    name: 'Launchpad',
    line: 'template',
    templateType: 'landing',
    tagline: 'A launch page with waitlist, changelog and pricing sections that convert.',
    stack: [STACK.next!, STACK.tailwind!, STACK.react!],
    capabilities: ['dark-mode', 'animations', 'i18n'],
    prices: [4900, 8900, 17900],
    popularity: 70,
    createdAt: '2026-03-18T09:00:00Z',
    description: [
      'Launchpad is a single-page launch site with a waitlist form, a pricing section and a changelog that reads your releases.',
    ],
    features: [
      {
        eyebrow: 'Conversion',
        title: 'Waitlist with double opt-in',
        body: 'Server Actions, rate limiting and a confirmation email.',
        icon: 'mail-check',
        size: 'lg',
      },
      {
        eyebrow: 'i18n',
        title: 'Two locales included',
        body: 'English and German with typed message keys.',
        icon: 'languages',
        size: 'md',
      },
    ],
    demoPages: [
      { label: 'Home', path: '/' },
      { label: 'Pricing', path: '/pricing' },
      { label: 'Changelog', path: '/changelog' },
    ],
    releases: [
      {
        version: '1.1.1',
        type: 'patch',
        releasedAt: '2026-08-28T10:00:00Z',
        title: 'Form accessibility',
        summary: 'Inline errors linked to inputs and an error summary on submit.',
        highlights: null,
        upgradeGuide: null,
        changes: [change('fixed', 'Waitlist errors are announced to screen readers')],
        compatibility: { next: '16.2', react: '19.2', tailwind: '4.1', node: '22' },
      },
      {
        version: '1.0.0',
        type: 'major',
        releasedAt: '2026-03-18T10:00:00Z',
        title: 'Launchpad 1.0',
        summary: 'The first stable release.',
        highlights: null,
        upgradeGuide: [block('First stable release.')],
        changes: [change('added', 'Waitlist, pricing and changelog sections')],
        compatibility: { next: '16.1', react: '19.2', tailwind: '4.0', node: '22' },
      },
    ],
  },
  {
    slug: 'docsmith',
    name: 'Docsmith',
    line: 'template',
    templateType: 'docs',
    tagline: 'A documentation site on Fumadocs with search, versioning and API pages.',
    stack: [STACK.next!, STACK.fumadocs!, STACK.tailwind!],
    capabilities: ['dark-mode', 'cms'],
    prices: [6900, 11900, 22900],
    popularity: 50,
    createdAt: '2026-06-01T09:00:00Z',
    description: [
      'Docsmith gives your product a documentation site readers trust: fast search, typed API tables and code blocks with copy buttons.',
    ],
    features: [
      {
        eyebrow: 'Search',
        title: 'Instant search',
        body: 'Orama search over every page, ⌘K ready.',
        icon: 'search',
        size: 'lg',
      },
      {
        eyebrow: 'API',
        title: 'Type tables',
        body: 'Generated from your TypeScript types.',
        icon: 'braces',
        size: 'md',
      },
    ],
    demoPages: [
      { label: 'Docs home', path: '/docs' },
      { label: 'API page', path: '/docs/api/client' },
    ],
    supportsTheme: true,
    releases: [
      {
        version: '1.0.0',
        type: 'major',
        releasedAt: '2026-06-01T10:00:00Z',
        title: 'Docsmith 1.0',
        summary: 'The first stable release on Fumadocs 16.',
        highlights: null,
        upgradeGuide: [block('First stable release.')],
        changes: [change('added', 'Search, API tables and versioned sidebars')],
        compatibility: { next: '16.2', react: '19.2', tailwind: '4.1', node: '22' },
      },
    ],
  },
]

const GENERAL_FAQ: Faq[] = [
  {
    _id: 'faq-license',
    question: 'What is the difference between Personal, Team and Extended?',
    answer: [
      block(
        'Personal covers one developer and one end product. Team covers up to five developers and unlimited internal or client projects. Extended covers end products sold to end users, such as a paid SaaS.',
      ),
    ],
  },
  {
    _id: 'faq-updates',
    question: 'Do I get future updates?',
    answer: [
      block(
        'Yes. Every release within the major version you bought is included, and your Library keeps every version downloadable. New major versions are offered as a discounted upgrade.',
      ),
    ],
  },
  {
    _id: 'faq-all-access',
    question: 'What happens to my downloads if I cancel All-Access?',
    answer: [
      block(
        'Releases published while your pass was active stay downloadable. New releases after the end date need an active pass or a one-time license.',
      ),
    ],
  },
  {
    _id: 'faq-tax',
    question: 'Who handles tax and invoices?',
    answer: [
      block(
        'Lemon Squeezy is our Merchant of Record. It calculates sales tax and VAT at checkout and issues your invoice, including your VAT ID if you add one.',
      ),
    ],
  },
  {
    _id: 'faq-refunds',
    question: 'Can I get a refund?',
    answer: [
      block('Yes, within 14 days of purchase. A refund revokes the license key and download access for that order.'),
    ],
  },
]

// ---------- Assemble ----------
function toCard(seed: Seed, rel: ChangelogEntry[]): ProductCard {
  const own = rel.filter((r) => r.product.slug === seed.slug && r.status === 'published')
  const latest = own[0]
  return {
    _id: `product-${seed.slug}`,
    name: seed.name,
    slug: seed.slug,
    line: seed.line,
    templateType: seed.templateType ?? null,
    tagline: seed.tagline,
    hero: art(seed.slug, `${seed.name} interface preview`),
    video: null,
    stack: seed.stack,
    capabilities: seed.capabilities,
    priceFromCents: Math.min(...seed.prices),
    inAllAccess: true,
    popularity: seed.popularity,
    createdAt: seed.createdAt,
    latestRelease: latest
      ? {
          version: latest.version,
          type: latest.type,
          title: latest.title,
          releasedAt: latest.releasedAt,
          compatibility: latest.compatibility,
        }
      : null,
  }
}

export const fixtureChangelog: ChangelogEntry[] = SEEDS.flatMap((seed) =>
  seed.releases.map((r) => ({
    ...r,
    _id: `release-${seed.slug}-${r.version}`,
    status: 'published' as const,
    releaseId: null,
    product: { name: seed.name, slug: seed.slug, line: seed.line },
  })),
).sort((a, b) => b.releasedAt.localeCompare(a.releasedAt))

export const fixtureProducts: ProductDetail[] = SEEDS.map((seed) => {
  const card = toCard(seed, fixtureChangelog)
  return {
    ...card,
    description: seed.description.map((t) => block(t)),
    heroDark: null,
    features: seed.features,
    fileTree: seed.fileTree ?? null,
    faq: GENERAL_FAQ.slice(0, 3),
    licenses: licenses(seed.prices),
    demo: seed.demoPages
      ? {
          origin: `https://${seed.slug}.lumira-demos.dev`,
          pages: seed.demoPages,
          supportsTheme: seed.supportsTheme ?? false,
          gallery: [
            { ...art(seed.slug, `${seed.name} on desktop`), device: 'desktop' },
            { ...art(seed.slug, `${seed.name} on mobile`), device: 'mobile' },
          ],
          lighthouse: { performance: 98, accessibility: 100, bestPractices: 100, seo: 100 },
        }
      : null,
    components: seed.components ?? [],
    related: [],
    recentReleases: fixtureChangelog.filter((r) => r.product.slug === seed.slug).slice(0, 3),
    seo: null,
  }
})

// Related products: same line first, then the most popular others.
for (const p of fixtureProducts) {
  p.related = fixtureProducts
    .filter((o) => o.slug !== p.slug)
    .sort((a, b) => Number(b.line === p.line) - Number(a.line === p.line) || b.popularity - a.popularity)
    .slice(0, 3)
    .map(
      ({
        description: _d,
        heroDark: _h,
        features: _f,
        fileTree: _t,
        faq: _q,
        licenses: _l,
        demo: _m,
        components: _c,
        related: _r,
        recentReleases: _rr,
        seo: _s,
        ...card
      }) => card,
    )
}

export const fixtureCards: ProductCard[] = fixtureProducts.map(
  ({
    description: _d,
    heroDark: _h,
    features: _f,
    fileTree: _t,
    faq: _q,
    licenses: _l,
    demo: _m,
    components: _c,
    related: _r,
    recentReleases: _rr,
    seo: _s,
    ...card
  }) => card,
)

const card = (slug: string) => fixtureCards.find((c) => c.slug === slug)!

export const fixtureSiteSettings: SiteSettings = {
  promoBanner: {
    enabled: false,
    text: 'Launch week: 30% off every license',
    code: 'LAUNCH30',
    href: '/?code=LAUNCH30',
  },
  affiliate: { commissionRate: 30, cookieDays: 30, payoutNote: 'Paid monthly through Lemon Squeezy.' },
  allAccess: {
    lsProductId: 59999,
    monthly: { lsVariantId: 200001, priceCents: 3900, buyUrl: null },
    yearly: { lsVariantId: 200002, priceCents: 39000, buyUrl: null },
    activationLimit: 10,
    perks: [
      'Every current and future asset',
      'Team rights on everything',
      'Every release while your pass is active',
      'Verified-owner Discord',
    ],
  },
  social: [
    { label: 'X', url: 'https://x.com/lumiradev' },
    { label: 'GitHub', url: 'https://github.com/lumiradev' },
  ],
  supportEmail: 'support@lumira.dev',
  statusUrl: null,
}

const tile = (
  t: Partial<HomePage['bands'][number]['tiles'][number]> &
    Pick<HomePage['bands'][number]['tiles'][number], 'kind' | 'cols' | 'rows'>,
) => ({
  _key: key(),
  hero: null,
  eyebrow: null,
  title: null,
  body: null,
  href: null,
  product: null,
  testimonial: null,
  stat: null,
  video: null,
  poster: null,
  snippet: null,
  stack: null,
  ...t,
})

export const fixtureHome: HomePage = {
  hero: {
    eyebrow: 'Premium web assets',
    title: 'Ship on foundations you can trust.',
    lead: 'Boilerplates, UI kits and templates by one curator. Try every one live, buy in thirty seconds, own every version.',
  },
  // Balanced per StyleGuide §4.3 (verified by tests/unit/fixtures.test.ts).
  bands: [
    {
      _key: key(),
      preset: 'lead-left',
      rows: 2,
      tiles: [
        tile({ kind: 'featuredProduct', cols: 8, rows: 2, hero: true, product: card('saas-starter') }),
        tile({
          kind: 'stat',
          cols: 4,
          rows: 2,
          eyebrow: 'Catalog',
          stat: { value: null, label: 'assets, each with a live demo', source: 'assetCount' },
        }),
      ],
    },
    {
      _key: key(),
      preset: 'golden-right',
      rows: 2,
      tiles: [
        tile({
          kind: 'docsTeaser',
          cols: 5,
          rows: 2,
          eyebrow: 'Build',
          title: 'Activate in one command',
          product: card('saas-starter'),
          snippet: 'npx lumira@latest activate',
        }),
        tile({ kind: 'featuredProduct', cols: 7, rows: 2, product: card('lumen-ui') }),
      ],
    },
    {
      _key: key(),
      preset: 'feature-left',
      rows: 2,
      tiles: [
        tile({ kind: 'allAccessPromo', cols: 6, rows: 2, hero: true, title: 'All-Access Pass' }),
        tile({
          kind: 'stat',
          cols: 3,
          rows: 2,
          eyebrow: 'Shipping',
          stat: { value: null, label: 'releases shipped across the catalog', source: 'releaseCount' },
        }),
        tile({
          kind: 'stat',
          cols: 3,
          rows: 2,
          eyebrow: 'Licensing',
          stat: { value: '60 s', label: 'from payment to license key, by design', source: 'manual' },
        }),
      ],
    },
    {
      _key: key(),
      preset: 'lead-right',
      rows: 2,
      tiles: [
        tile({ kind: 'changelogTeaser', cols: 4, rows: 2, eyebrow: 'Changelog', title: 'Recently shipped' }),
        tile({ kind: 'featuredProduct', cols: 8, rows: 2, hero: true, product: card('folio') }),
      ],
    },
    {
      _key: key(),
      preset: 'rhythm',
      rows: 1,
      tiles: [
        tile({
          kind: 'stat',
          cols: 4,
          rows: 1,
          eyebrow: 'Delivery',
          stat: { value: '72 h', label: 'email download links, then your Library', source: 'manual' },
        }),
        tile({
          kind: 'stat',
          cols: 4,
          rows: 1,
          eyebrow: 'Integrity',
          stat: { value: 'SHA-256', label: 'checksum beside every release', source: 'manual' },
        }),
        tile({ kind: 'stackBadges', cols: 4, rows: 1, eyebrow: 'Stack', product: card('saas-starter') }),
      ],
    },
  ],
  previewTeaser: {
    title: 'Drive it before you buy it',
    body: 'Every template runs live at desktop, tablet and mobile widths. Switch devices without a reload and keep the buy button in reach.',
    video: null,
    poster: art('folio', 'Folio running in the Live Preview player'),
    product: card('folio'),
  },
  testimonials: [],
  faq: GENERAL_FAQ,
  closingCta: {
    title: 'Own every version, from day one.',
    body: 'Buy once and keep every release of that major version, or get everything with All-Access.',
  },
  seo: null,
}

export const fixtureBundles: Bundle[] = [
  {
    _id: 'bundle-agency',
    name: 'Agency Bundle',
    slug: 'agency',
    tagline: 'Lumen UI, Motion Primitives and Launchpad with Team rights.',
    hero: art('lumen-ui', 'Agency Bundle products'),
    tier: 'team',
    lsProductId: 58888,
    lsVariantId: 300001,
    priceCents: 34900,
    buyUrl: null,
    includes: ['lumen-ui', 'motion-primitives', 'launchpad'].map((slug) => ({
      ...card(slug),
      licenses: fixtureProducts.find((p) => p.slug === slug)!.licenses,
    })),
    seo: null,
  },
]

export const fixturePosts: Post[] = [
  {
    _id: 'post-introducing-lumira',
    title: 'Introducing Lumira',
    slug: 'introducing-lumira',
    excerpt: 'Why we built a single-curator store for web assets, and what "own every version" means in practice.',
    publishedAt: '2026-09-20T09:00:00Z',
    cover: art('saas-starter', 'The Lumira storefront'),
    author: { name: 'Lumira', role: 'Editorial' },
    body: [
      block(
        'Screenshots hide what matters about a template: how it responds, how it performs and how the code reads. Lumira lets you drive every asset live before you buy it.',
      ),
      block('Own every version', 'h3'),
      block(
        'Every purchase includes every release within its major version, a license key issued the moment payment clears, and a Library that keeps every version downloadable.',
      ),
    ],
    seo: null,
  },
]

const legal = (slug: string, title: string, paragraphs: string[]): LegalPage => ({
  title,
  slug,
  updatedAt: '2026-09-24',
  body: [block('Draft pending legal review before launch (Task.md P8.07).'), ...paragraphs.map((p) => block(p))],
})

export const fixtureLegal: LegalPage[] = [
  legal('license', 'License terms', [
    'Personal: one developer, one end product. Team: up to five developers and unlimited internal or client projects. Extended: end products sold to end users. All-Access: Team rights on every asset while the pass is active.',
    'You may not redistribute the source code as a template, kit or boilerplate, alone or bundled, whether free or paid.',
  ]),
  legal('refund-policy', 'Refund policy', [
    'You can request a refund within 14 days of purchase. Refunds revoke the license key and download access for that order.',
  ]),
  legal('terms', 'Terms of sale', [
    'Lemon Squeezy is the Merchant of Record for all orders and is responsible for payment processing, sales tax and invoicing.',
  ]),
  legal('privacy', 'Privacy policy', [
    'We process the minimum personal data needed to deliver your purchase: your email, order records and license activations. Payment details are handled by Lemon Squeezy and never reach our servers.',
  ]),
]
