/** Deterministic, obviously fake values that satisfy src/lib/env.ts for unit and integration tests. */
export const testEnv: Record<string, string> = {
  NODE_ENV: 'test',
  NEXT_PUBLIC_APP_URL: 'https://lumira.test',
  NEXT_PUBLIC_DEMO_ORIGIN_SUFFIX: 'lumira-demos.dev',
  CONTENT_SOURCE: 'fixtures',
  DATABASE_URL: 'postgresql://test:test@localhost:5432/lumira_test',
  CLERK_SECRET_KEY: 'sk_test_lumira',
  CLERK_WEBHOOK_SIGNING_SECRET: 'whsec_dGVzdC1zZWNyZXQtZm9yLWx1bWlyYS10ZXN0cw==',
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_Y2xlcmsubHVtaXJhLnRlc3Qk',
  NEXT_PUBLIC_SANITY_PROJECT_ID: 'test1234',
  NEXT_PUBLIC_SANITY_DATASET: 'test',
  SANITY_API_READ_TOKEN: 'sanity-read',
  SANITY_API_WRITE_TOKEN: 'sanity-write',
  SANITY_WEBHOOK_SECRET: 'sanity-webhook-secret-0123456789',
  LS_API_KEY: 'ls-test-api-key',
  LS_STORE_ID: '4242',
  NEXT_PUBLIC_LS_STORE_SLUG: 'lumira',
  LS_WEBHOOK_SECRET: 'lumira-test-signing-secret',
  LS_TEST_MODE: 'true',
  LS_FEE_PCT: '5',
  LS_FEE_FIXED_CENTS: '50',
  R2_ACCOUNT_ID: 'r2-account',
  R2_BUCKET: 'lumira-assets-test',
  R2_READ_ACCESS_KEY_ID: 'r2-read-id',
  R2_READ_SECRET_ACCESS_KEY: 'r2-read-secret',
  R2_WRITE_ACCESS_KEY_ID: 'r2-write-id',
  R2_WRITE_SECRET_ACCESS_KEY: 'r2-write-secret',
  RESEND_API_KEY: 're_test_lumira',
  RESEND_WEBHOOK_SECRET: 'whsec_dGVzdC1yZXNlbmQtc2VjcmV0',
  EMAIL_FROM: 'Lumira <orders@mail.lumira.test>',
  NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: 'phc_test',
  POSTHOG_PERSONAL_API_KEY: 'phx_test',
  POSTHOG_PROJECT_ID: '1',
  UPSTASH_REDIS_REST_URL: 'https://redis.lumira.test',
  UPSTASH_REDIS_REST_TOKEN: 'redis-token',
  QSTASH_TOKEN: 'qstash-token',
  QSTASH_CURRENT_SIGNING_KEY: 'sig_current',
  QSTASH_NEXT_SIGNING_KEY: 'sig_next',
  DISCORD_CLIENT_ID: 'discord-client',
  DISCORD_CLIENT_SECRET: 'discord-secret',
  DISCORD_BOT_TOKEN: 'discord-bot',
  DISCORD_GUILD_ID: '100',
  DISCORD_VERIFIED_ROLE_ID: '200',
  DISCORD_WELCOME_CHANNEL_ID: '300',
  DISCORD_STATE_SECRET: 'discord-state-secret-0123456789abcdef',
  // 32 zero bytes, base64
  LICENSE_ENCRYPTION_KEY: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  LICENSE_HASH_PEPPER: 'license-hash-pepper-0123456789abcdef',
  DOWNLOAD_TOKEN_SECRET: 'download-token-secret-0123456789abcd',
  GUEST_SCOPE_SECRET: 'guest-scope-secret-0123456789abcdefg',
  IP_HASH_SALT: 'ip-hash-salt-0123456789',
  CRON_SECRET: 'cron-secret-0123456789abcdefghijklmn',
}
