// Writes .env.local for local development: fresh random secrets, placeholders for third-party
// services, and CONTENT_SOURCE=fixtures so the storefront renders before a Sanity project exists.
// Usage: pnpm env:local [--force]
// Clerk keys are left empty on purpose: `next dev` then runs Clerk in keyless mode.
import { randomBytes } from 'node:crypto'
import { existsSync, writeFileSync } from 'node:fs'

const target = new URL('../.env.local', import.meta.url)
if (existsSync(target) && !process.argv.includes('--force')) {
  console.error('.env.local already exists. Re-run with --force to overwrite it.')
  process.exit(1)
}

const secret = (bytes = 32) => randomBytes(bytes).toString('base64')
const token = (bytes = 24) => randomBytes(bytes).toString('base64url')

const values = {
  NEXT_PUBLIC_APP_URL: 'http://localhost:3000',
  NEXT_PUBLIC_DEMO_ORIGIN_SUFFIX: 'lumira-demos.dev',
  CONTENT_SOURCE: 'fixtures',

  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: '',
  CLERK_SECRET_KEY: '',
  CLERK_WEBHOOK_SIGNING_SECRET: '',
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in',
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up',

  DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/lumira',
  DATABASE_URL_DIRECT: 'postgresql://postgres:postgres@localhost:5432/lumira',

  NEXT_PUBLIC_SANITY_PROJECT_ID: 'replace-me',
  NEXT_PUBLIC_SANITY_DATASET: 'staging',
  SANITY_API_READ_TOKEN: 'replace-me',
  SANITY_API_WRITE_TOKEN: 'replace-me',
  SANITY_WEBHOOK_SECRET: token(),

  LS_API_KEY: 'replace-me',
  LS_STORE_ID: '1',
  NEXT_PUBLIC_LS_STORE_SLUG: 'lumira',
  LS_WEBHOOK_SECRET: token(18),
  LS_TEST_MODE: 'true',
  LS_FEE_PCT: '5',
  LS_FEE_FIXED_CENTS: '50',

  R2_ACCOUNT_ID: 'replace-me',
  R2_BUCKET: 'lumira-assets-staging',
  R2_READ_ACCESS_KEY_ID: 'replace-me',
  R2_READ_SECRET_ACCESS_KEY: 'replace-me',
  R2_WRITE_ACCESS_KEY_ID: 'replace-me',
  R2_WRITE_SECRET_ACCESS_KEY: 'replace-me',

  RESEND_API_KEY: 're_replace_me',
  RESEND_WEBHOOK_SECRET: `whsec_${secret(24)}`,
  EMAIL_FROM: '"Lumira <orders@mail.lumira.dev>"',

  NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: 'replace-me',
  POSTHOG_PERSONAL_API_KEY: 'replace-me',
  POSTHOG_PROJECT_ID: '0',

  UPSTASH_REDIS_REST_URL: 'https://replace-me.upstash.io',
  UPSTASH_REDIS_REST_TOKEN: 'replace-me',
  QSTASH_TOKEN: 'replace-me',
  QSTASH_CURRENT_SIGNING_KEY: 'replace-me',
  QSTASH_NEXT_SIGNING_KEY: 'replace-me',

  DISCORD_CLIENT_ID: 'replace-me',
  DISCORD_CLIENT_SECRET: 'replace-me',
  DISCORD_BOT_TOKEN: 'replace-me',
  DISCORD_GUILD_ID: '0',
  DISCORD_VERIFIED_ROLE_ID: '0',
  DISCORD_WELCOME_CHANNEL_ID: '0',
  DISCORD_STATE_SECRET: secret(),

  LICENSE_ENCRYPTION_KEY: secret(32),
  LICENSE_HASH_PEPPER: secret(),
  DOWNLOAD_TOKEN_SECRET: secret(),
  GUEST_SCOPE_SECRET: secret(),
  IP_HASH_SALT: secret(24),
  CRON_SECRET: secret(),

  NEXT_PUBLIC_SENTRY_DSN: '',
}

const body = [
  '# Generated by `pnpm env:local`. Placeholders marked replace-me must be filled before the',
  '# matching feature works (checkout, downloads, email…). The storefront itself runs as-is.',
  ...Object.entries(values).map(([k, v]) => `${k}=${v}`),
  '',
].join('\n')

writeFileSync(target, body, { mode: 0o600 })
console.log('Wrote .env.local with fresh secrets. Fill the replace-me values as you connect each service.')
